
runtime: python38
instance_class: F2
#entrypoint: uvicorn main:app --reload
#entrypoint: gunicorn main:app --workers 1 --worker-class
entrypoint: gunicorn -w 1 -k uvicorn.workers.UvicornWorker main:app

# basic_scaling:
#   max_instances: 5
#   idle_timeout: 60m

# include senstive configuration data in environment variables.
# source: https://stackoverflow.com/questions/22669528/securely-storing-environment-variables-in-gae-with-app-yaml
# NB!!! Add env_variables.yaml into .gitignore!
includes:
  - env_variables.yaml